/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogodavelhaminimax;

import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import jdk.jfr.Event;

/**
 *
 * @author tanak
 */
public class Tela extends javax.swing.JFrame {

    Tabuleiro tabuleiro = null;
    boolean isX = true;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        tabuleiro = new Tabuleiro();
    }

    private void marcar(MouseEvent evt) {
        try {
            int coluna;
            int linha;
            if (evt.getXOnScreen() < 294) {//    * primeira linha
                linha = 0;
            } else if (evt.getXOnScreen() < 588) {//    * segunda linha
                linha = 1;
            } else {//  * terceira linha
                linha = 2;
            }

            if (evt.getYOnScreen() < 294) { //    * primeira coluna
                coluna = 0;
            } else if (evt.getYOnScreen() < 588) {//    * segunda coluna
                coluna = 1;
            } else {//  * terceira coluna
                coluna = 2;
            }
            char finalizou = tabuleiro.marcar(linha, coluna, isX);
            JLabel x = null;
            if (isX) {
                x = new JLabel("X", SwingConstants.LEFT);
            } else {
                x = new JLabel("O", SwingConstants.LEFT);
            }
            getContentPane().add(x);
            x.setVisible(true);
            x.setFont(jLabel1.getFont());
            x.requestFocus();
            jLabel1.add(x);
            x.setBounds(linha * 294, coluna * 294, 235, 235);
            isX = !(isX);
            if (finalizou != ' ') {
                JOptionPane.showMessageDialog(rootPane, "Acabou o jogo, vitória de: " + finalizou);
                recomecar();
            }
            if(tabuleiro.deuVelha()){
                JOptionPane.showMessageDialog(rootPane, "Deu velha");
                recomecar();
            }
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(rootPane, "alguém já marcou aí.... tá querendo trapacear?... q decepção...");
            e.printStackTrace();
        }
    }

    private void recomecar(){
        var components = jLabel1.getComponents();
        for(var component : components){
            component.setVisible(false);
        }
        tabuleiro = new Tabuleiro();
//        jLabel1.removeAll();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jLabel1.setFont(new java.awt.Font("Roboto Bk", 0, 250)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogodavelhaminimax/jogoDaVelha.jpeg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased

        marcar(evt);

    }//GEN-LAST:event_jLabel1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
